title: "BioPulse Analytics"
name: "Kamela"
description: "A personal website exploring health data science, cloud computing, and biomedical innovation."

url: "https://kamie-x.github.io"
baseurl: ""

avatar: "/images/avatar.png"

author:
  name: "Kamela"

footer-links:
  github: "Kamie-X"
  email: ""
  linkedin: ""

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
